spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/budget-buddy
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
      pool-name: HikariPool
      maximum-pool-size: 10          # Usually 5â€“20 for local dev
      minimum-idle: 2
      idle-timeout: 30000            # 30 seconds
      max-lifetime: 1800000          # 30 minutes
      connection-timeout: 500        # 5 seconds
      auto-commit: false             # Let JPA manage transactions
      validation-timeout: 3000          # Add validation timeout
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
    drop-first: false
    clear-checksums: false
  modulith:
    events:
      default-async: true
    docs:
      enabled: false  # Disable in dev/local profiles
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    liquibase: INFO
    org.springframework.security: INFO
    com.zaxxer.hikari: INFO
jwt-secret: ${JWT_SECRET}
jwt:
  secret: ${JWT_SECRET}         # Base64-encoded, 64+ bytes for HS512
  issuer: my-auth-service
  kid: v1
  access-ttl: 3m
  refresh-ttl: 7d
  clock-skew-seconds: 30